sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: this location is a password, I hide it bacause security problem.
  wechat:
    appid: this location is APPID, I hide it bacause security problem.
    secret: this location is secret, I hide it bacause security problem.
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: this location is access-key-id, I hide it bacause security problem.
    access-key-secret: this location is access-key-secret, I hide it bacause security problem.
    bucket-name: this location is bucket-name, I hide it bacause security problem.
  redis:
    host: localhost
    port: 6379
    password: this location is a password, I hide it bacause security problem.
    database: 10
