sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "0000"
  wechat:
    appid: wxae7603d7c4aa0db4
    secret: 46437c7fbbf326c7afe05017afb579f3
#  alioss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
#    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
#    bucket-name: sky-take-out
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tH8NaY8tmnYx2FCEBcp
    access-key-secret: mxVwJwBlku2s1b29uns0KDLjsCfqB6
    bucket-name: zhangbeichen-20250426
  redis:
    host: localhost
    port: 6379
    password: "123456"
    database: 10